# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8ee09c5e36df16e0ca19562c9257b05a6e7a3967632cfcffdc161164b6299333ba17028ac0658c6196e431a4e5c8214b07af38219981a5c2a628daaeaaad6cc

test:
  secret_key_base: 8e7fab716f9b620438bc5c28c419d1cdf0d4e8bf4d6ee63e28b79e9d9bede8536dde01d989660b95c2169dcc95795d8162b593115bf122d7e69dbbea99a5e7dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
