# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1117f689062e59822baf56aac6c612c802090c3fdd677d8dfb87725494ce2cf5c198ba01b5708fdfb32beadef5445e60a22613c96628ba6cbcd341e0b5f0545

test:
  secret_key_base: 44f9ff7d502a92863a9ad4b55db0fb87d432084c4e4ef3d14f4fd22917e1ed931afe31a302d67d39c26562522cf2f24c4f9016f552e92adaed950c60ca570fe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
