# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dd10e9db1d189d346d9fbdd2d71792d0173535539b4d7db8f6605bb3c213a56202207a079a635a8765e4c215643e49901f8733453b7cb376230740ee9684a57

test:
  secret_key_base: 76daaf304503a3a82e20711dec8ccae52ffde8e6334931cac21f100fcb441a5d65378a037e24a62110ccf9eb802774617dfe34fb01dd98613ed3281ad0d4bbcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
